Previous error fixed but another error occured:
	New Error:
		from browser --> js console
		--------------------------------
			react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
			index.js:69 Running application "main" with appParams:
			 Object
			Development-level warnings: ON.
			Performance optimizations: OFF.
			react-dom.development.js:22839 Uncaught TypeError: _firebaseConfig__WEBPACK_IMPORTED_MODULE_5__.db.collection is not a function
				at App.js:55:1
				at commitHookEffectListMount (react-dom.development.js:23150:1)
				at commitPassiveMountOnFiber (react-dom.development.js:24931:1)
				at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
				at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
				at commitPassiveMountEffects (react-dom.development.js:24866:1)
				at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
				at flushPassiveEffects (react-dom.development.js:26984:1)
				at react-dom.development.js:26769:1
				at workLoop (scheduler.development.js:266:1)
			react-dom.development.js:18687 The above error occurred in the <App> component:

				at App (http://localhost:19006/static/js/bundle.js:155:67)
				at withDevTools(App)
				at div
				at http://localhost:19006/static/js/bundle.js:6040:25
				at div
				at http://localhost:19006/static/js/bundle.js:6040:25
				at http://localhost:19006/static/js/bundle.js:1440:24

			Consider adding an error boundary to your tree to customize error handling behavior.
			Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
			logCapturedError @ react-dom.development.js:18687
			Show 1 more frame
			Show less
			react-dom.development.js:12056 Uncaught TypeError: _firebaseConfig__WEBPACK_IMPORTED_MODULE_5__.db.collection is not a function
				at App.js:55:1
				at commitHookEffectListMount (react-dom.development.js:23150:1)
				at commitPassiveMountOnFiber (react-dom.development.js:24931:1)
				at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
				at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
				at commitPassiveMountEffects (react-dom.development.js:24866:1)
				at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
				at flushPassiveEffects (react-dom.development.js:26984:1)
				at react-dom.development.js:26769:1
				at workLoop (scheduler.development.js:266:1)
			ResponderTouchHistoryStore.js:104 Cannot record touch end without a touch start.
			 Touch End: {"identifier":0,"pageX":1102,"pageY":328,"timestamp":18985.10000000894}
			 Touch Bank: []
			recordTouchEnd @ ResponderTouchHistoryStore.js:104
			Show 1 more frame
			Show less

		-------------------------------------

	Previous Error - that has been fixed:
		cmd -> expo console:
		---------------------------------------------------

			(node:13508) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
			(Use `node --trace-deprecation ...` to show where the warning was created)
			(node:13508) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use the async 'start' or 'startCallback' method.
			› Press ? │ show all commands
			WARNING in ./App.js:12:25
			export 'firebaseConfig' (imported as 'firebaseConfig') was not found in './firebaseConfig' (possible exports: db)
			  10 | // Initialize Firebase only once
			  11 | if (!firebase.apps.length) {
			> 12 |   firebase.initializeApp(firebaseConfig); // Initialize Firebase with config
				 |                         ^
			  13 | } else {
			  14 |   firebase.app(); // Use the already initialized Firebase app
			  15 | }

			WARNING in ./firebaseConfig.js:16:5
			export 'default' (imported as 'firebase') was not found in 'firebase/app' (possible exports: FirebaseError, SDK_VERSION, _DEFAULT_ENTRY_NAME, _addComponent, _addOrOverwriteComponent, _apps, _clearComponents, _components, _getProvider, _registerComponent, _removeServiceInstance, deleteApp, getApp, getApps, initializeApp, onLog, registerVersion, setLogLevel)
			  14 |
			  15 | // Initialize Firebase
			> 16 | if (!firebase.apps.length) {
				 |     ^
			  17 |   firebase.initializeApp(firebaseConfig);
			  18 | }
			  19 |

			WARNING in ./firebaseConfig.js:17:2
			export 'default' (imported as 'firebase') was not found in 'firebase/app' (possible exports: FirebaseError, SDK_VERSION, _DEFAULT_ENTRY_NAME, _addComponent, _addOrOverwriteComponent, _apps, _clearComponents, _components, _getProvider, _registerComponent, _removeServiceInstance, deleteApp, getApp, getApps, initializeApp, onLog, registerVersion, setLogLevel)
			  15 | // Initialize Firebase
			  16 | if (!firebase.apps.length) {
			> 17 |   firebase.initializeApp(firebaseConfig);
				 |  ^
			  18 | }
			  19 |
			  20 | // Now you can use Firestore

			WARNING in ./firebaseConfig.js:21:18
			export 'default' (imported as 'firebase') was not found in 'firebase/app' (possible exports: FirebaseError, SDK_VERSION, _DEFAULT_ENTRY_NAME, _addComponent, _addOrOverwriteComponent, _apps, _clearComponents, _components, _getProvider, _registerComponent, _removeServiceInstance, deleteApp, getApp, getApps, initializeApp, onLog, registerVersion, setLogLevel)
			  19 |
			  20 | // Now you can use Firestore
			> 21 | export const db = firebase.firestore();
				 |                  ^
			  22 |

			web compiled with 4 warnings

		-----------------------------------------------------